services:
  frontend:
    build: 
      context: ./FrontEnd
      dockerfile: Dockerfile
    environment:
      VITE_API_URL: http://localhost:5166/api
    ports: 
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    ports:
      - "5166:5166"
    environment:
      - AllowedOrigins=http://localhost:5173